name: aidoodle
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - click=7.0=py_0
  - coverage=4.5.4
  - importlib_metadata=0.23=py37_0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - more-itertools=7.2.0=py37_0
  - mypy=0.740=py_0
  - mypy_extensions=0.4.1=py37_0
  - ncurses=6.1
  - openssl=1.1.1d
  - packaging=19.2=py_0
  - pip=19.3.1=py37_0
  - pluggy=0.13.0=py37_0
  - psutil=5.6.5
  - py=1.8.0=py_0
  - pyparsing=2.4.5=py_0
  - pytest=5.0.1=py37_0
  - pytest-cov=2.8.1=py_0
  - python=3.7.5
  - readline=7.0
  - setuptools=41.6.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1
  - tk=8.6.8
  - typed-ast=1.4.0
  - typing_extensions=3.7.4.1=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4
  - zipp=0.6.0=py_0
  - zlib=1.2.11


